app:
  name: gs-server
  env: local
#  path:
#    app_path: "lllk/llkl"
#    upload_path: "2244/llkl"
#    download_path: "lll/llkl"
#    log_path: "/wwwlogs/lll"
#  domain:
#    api_domain: "https://apixxxxx.com"
#    web_domain: "https://web.xxxxx.com"
#    app_domain: "https://app.xxxxx.com"
server:
  http:
    port: 8002
#    timeout: 1s
#    timeout: 1s

